apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: telemt

resources:
  - namespace.yaml
  - configmap.yaml
  - service.yaml
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: telemt-k8s
    includeSelectors: true

images:
  - name: ghcr.io/telemt/telemt
    newTag: latest
